# Generated by Django 2.0.7 on 2021-01-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='categorie',
            field=models.CharField(choices=[('S', 'Sport'), ('P', 'Politics'), ('B', 'Business'), ('H', 'Health'), ('D', 'Design'), ('T', 'Tech'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
