# Generated by Django 2.0.7 on 2021-01-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210108_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pusblished',
            field=models.BooleanField(default=True),
        ),
    ]
