# Generated by Django 2.0.7 on 2021-01-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_pusblished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='pusblished',
            new_name='published',
        ),
    ]
