# Generated by Django 2.0.7 on 2021-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210108_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_preview',
            field=models.TextField(default=' Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure alias, corporis, quod odio repellendus voluptatum aspernatur voluptatem neque consequuntur perspiciatis natus quam id nostrum repellat molestiae itaque exercitationem sunt a. Commodi labore repudiandae debitis et incidunt itaque a dolorum corporis nobis in, non beatae laudantium, magnam, ipsum rem obcaecati fugiat.'),
        ),
    ]
