# Generated by Django 3.0.7 on 2021-01-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_body_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categorie',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Politics', 'Politics'), ('Business', 'Business'), ('Health', 'Health'), ('Design', 'Design'), ('Tech', 'Tech'), ('Movies', 'Movies')], default='O', max_length=30),
        ),
    ]
