# Generated by Django 2.0.7 on 2021-01-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210110_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(default='Helloworld.com', max_length=2040),
        ),
    ]
